import type { EventType } from "@/app/data/marketplace";
import type { EventTaxonomyProfile } from "./types";

export const eventExamples = [
  "Birthday party",
  "Wedding",
  "Quinceanera",
  "Bar Mitzvah",
  "Bat Mitzvah",
  "Graduation",
  "Corporate retreat",
  "Pool party",
  "Retirement party",
  "Baby shower",
  "Funeral",
  "Block party",
  "Holiday party",
  "BBQ",
  "Anniversary",
  "Housewarming",
  "Family reunion",
  "Sweet 16",
  "Prom",
  "Charity gala",
  "Festival",
  "Conference",
  "Seminar",
  "Trade show",
  "Church event",
  "School carnival",
  "Sports banquet",
] as const;

export const eventTaxonomyProfiles: EventTaxonomyProfile[] = [
  {
    aliases: [
      "birthday",
      "birthday party",
      "18th birthday",
      "21st birthday",
      "kids birthday",
      "birthday bbq",
      "pool birthday",
      "sweet sixteen",
      "sweet 16",
    ],
    budgetTier: "standard",
    description: "A social celebration built around age, theme, food, cake, and entertainment.",
    formality: "casual",
    guestSize: "20-80",
    id: "birthday",
    indoorOutdoor: "indoor-outdoor",
    luxuryAddOns: ["Live Music", "Photo Booth", "Florals"],
    marketplaceEventType: "Birthday",
    optionalVendors: ["Magic", "Character Performers", "Invitations", "Photography"],
    primaryType: "Birthday",
    recommendedTags: [
      "birthday",
      "cake",
      "kids",
      "family-friendly",
      "theme",
      "bbq",
      "pool",
      "backyard",
    ],
    recommendedVendors: ["DJ", "Rentals", "Photo Booth", "Photography"],
    requiredVendors: ["Venue", "Catering", "Cake & Desserts"],
    season: "year-round",
    subtype: "social",
    timeOfDay: "afternoon",
    venueStyle: "home, backyard, restaurant, hall, or activity venue",
  },
  {
    aliases: [
      "wedding",
      "armenian wedding",
      "jewish wedding",
      "indian wedding",
      "wedding reception",
      "ceremony",
      "reception",
      "anniversary",
    ],
    budgetTier: "premium",
    description: "A ceremony and reception plan with hospitality, decor, music, and guest flow.",
    formality: "formal",
    guestSize: "75-250",
    id: "wedding",
    indoorOutdoor: "indoor-outdoor",
    luxuryAddOns: ["Live Music", "Transportation", "Photo Booth", "AV Production"],
    marketplaceEventType: "Wedding",
    optionalVendors: ["DJ", "Cake & Desserts", "Invitations", "Staffing"],
    primaryType: "Wedding",
    recommendedTags: [
      "wedding",
      "ceremony",
      "reception",
      "florals",
      "formal",
      "cultural",
      "armenian",
      "religious",
    ],
    recommendedVendors: ["Florals", "Photography", "Rentals", "Live Music"],
    requiredVendors: ["Venue", "Catering"],
    season: "spring-fall",
    subtype: "ceremony and reception",
    timeOfDay: "evening",
    venueStyle: "ballroom, estate, hotel, garden, or banquet hall",
  },
  {
    aliases: ["quinceanera", "quince", "quinceanera party", "quinceanera celebration"],
    budgetTier: "premium",
    culture: "Latine",
    description: "A milestone cultural celebration with formal entrance, family program, and dancing.",
    formality: "formal",
    guestSize: "75-200",
    id: "quinceanera",
    indoorOutdoor: "indoor",
    luxuryAddOns: ["Live Music", "Photo Booth", "Florals"],
    marketplaceEventType: "Birthday",
    optionalVendors: ["Cake & Desserts", "Invitations", "Transportation"],
    primaryType: "Birthday",
    recommendedTags: ["quinceanera", "latine", "formal", "family", "dance", "milestone"],
    recommendedVendors: ["DJ", "Photography", "Florals", "Rentals"],
    requiredVendors: ["Venue", "Catering"],
    season: "year-round",
    subtype: "Quinceanera",
    timeOfDay: "evening",
    venueStyle: "banquet hall, ballroom, or event venue",
  },
  {
    aliases: ["bar mitzvah", "bat mitzvah", "b mitzvah", "mitzvah"],
    budgetTier: "premium",
    description: "A Jewish coming-of-age celebration with family, food, program, and entertainment.",
    formality: "semi-formal",
    guestSize: "60-180",
    id: "mitzvah",
    indoorOutdoor: "indoor",
    luxuryAddOns: ["Photo Booth", "Live Music", "AV Production"],
    marketplaceEventType: "Private Party",
    optionalVendors: ["Invitations", "Photography", "Cake & Desserts"],
    primaryType: "Private Party",
    recommendedTags: ["mitzvah", "jewish", "kosher", "family-friendly", "dance"],
    recommendedVendors: ["DJ", "Catering", "Rentals"],
    religion: "Jewish",
    requiredVendors: ["Venue"],
    season: "year-round",
    subtype: "Bar or Bat Mitzvah",
    timeOfDay: "evening",
    venueStyle: "synagogue hall, hotel, banquet room, or event venue",
  },
  {
    aliases: [
      "corporate",
      "corporate retreat",
      "company party",
      "team offsite",
      "japanese corporate dinner",
      "corporate dinner",
      "training",
    ],
    budgetTier: "premium",
    description: "A professional gathering for teams, clients, leadership, training, or hospitality.",
    formality: "semi-formal",
    guestSize: "30-400",
    id: "corporate",
    indoorOutdoor: "indoor",
    luxuryAddOns: ["Live Music", "Transportation", "Photo Booth"],
    marketplaceEventType: "Corporate",
    optionalVendors: ["DJ", "Security", "Photography"],
    primaryType: "Corporate",
    recommendedTags: ["corporate", "professional", "av", "networking", "presentation", "dinner"],
    recommendedVendors: ["Catering", "AV Production", "Staffing", "Rentals"],
    requiredVendors: ["Venue"],
    season: "year-round",
    subtype: "retreat or dinner",
    timeOfDay: "evening",
    venueStyle: "hotel, conference room, restaurant, retreat venue, or private dining room",
  },
  {
    aliases: ["conference", "convention", "trade show", "expo", "seminar", "summit"],
    budgetTier: "premium",
    description: "A content-led or exhibitor-led business event with registration and production needs.",
    formality: "semi-formal",
    guestSize: "100-2000",
    id: "conference",
    indoorOutdoor: "indoor",
    luxuryAddOns: ["Live Streaming", "Security", "Photography"],
    marketplaceEventType: "Convention",
    optionalVendors: ["Catering", "Staffing", "Printed Materials"],
    primaryType: "Convention",
    recommendedTags: ["conference", "seminar", "trade-show", "registration", "av", "exhibitor"],
    recommendedVendors: ["AV Production", "Registration", "Booth Rentals", "Rentals"],
    requiredVendors: ["Venue"],
    season: "year-round",
    subtype: "conference or trade show",
    timeOfDay: "morning",
    venueStyle: "convention center, hotel ballroom, campus, or meeting venue",
  },
  {
    aliases: ["graduation", "graduation party", "grad party", "prom", "school banquet", "sports banquet"],
    budgetTier: "standard",
    description: "A school or milestone celebration with photos, food, music, and guest recognition.",
    formality: "semi-formal",
    guestSize: "40-200",
    id: "graduation",
    indoorOutdoor: "indoor-outdoor",
    luxuryAddOns: ["Live Music", "Photo Booth", "AV Production"],
    marketplaceEventType: "Graduation",
    optionalVendors: ["Cake & Desserts", "Invitations", "Transportation"],
    primaryType: "Graduation",
    recommendedTags: ["graduation", "school", "photos", "family", "recognition"],
    recommendedVendors: ["Catering", "Photography", "DJ", "Rentals"],
    requiredVendors: ["Venue"],
    season: "spring-summer",
    subtype: "school celebration",
    timeOfDay: "afternoon",
    venueStyle: "home, hall, campus, restaurant, or banquet room",
  },
  {
    aliases: ["baby shower", "bridal shower", "gender reveal"],
    budgetTier: "standard",
    description: "A hosted shower with light food, decor, desserts, gifts, and family-friendly flow.",
    formality: "semi-formal",
    guestSize: "20-80",
    id: "baby-shower",
    indoorOutdoor: "indoor-outdoor",
    luxuryAddOns: ["Florals", "Photo Booth", "Magic"],
    marketplaceEventType: "Baby Shower",
    optionalVendors: ["Photography", "Invitations", "Character Performers"],
    primaryType: "Baby Shower",
    recommendedTags: ["baby-shower", "family-friendly", "dessert", "florals", "brunch"],
    recommendedVendors: ["Catering", "Cake & Desserts", "Rentals", "Florals"],
    requiredVendors: ["Venue"],
    season: "year-round",
    subtype: "shower",
    timeOfDay: "afternoon",
    venueStyle: "home, garden, brunch room, or small event space",
  },
  {
    aliases: ["funeral", "memorial", "celebration of life", "wake", "repass"],
    budgetTier: "standard",
    description: "A respectful memorial gathering with venue, food, florals, programs, and streaming.",
    formality: "formal",
    guestSize: "30-200",
    id: "funeral",
    indoorOutdoor: "indoor",
    luxuryAddOns: ["Live Music", "Photography", "Transportation"],
    marketplaceEventType: "Funeral",
    optionalVendors: ["AV Production", "Rentals", "Staffing"],
    primaryType: "Funeral",
    recommendedTags: ["funeral", "memorial", "respectful", "florals", "programs", "streaming"],
    recommendedVendors: ["Catering", "Florals", "Printed Programs", "Live Streaming"],
    requiredVendors: ["Venue"],
    season: "year-round",
    subtype: "memorial",
    timeOfDay: "afternoon",
    venueStyle: "funeral home, church hall, banquet room, or family home",
  },
  {
    aliases: ["fundraiser", "charity gala", "gala", "benefit", "nonprofit event"],
    budgetTier: "premium",
    description: "A mission-led event with donors, program moments, food, presentation, and ambiance.",
    formality: "formal",
    guestSize: "75-500",
    id: "fundraiser",
    indoorOutdoor: "indoor",
    luxuryAddOns: ["Live Music", "Florals", "Security"],
    marketplaceEventType: "Fundraiser",
    optionalVendors: ["Photography", "Registration", "Printed Materials"],
    primaryType: "Fundraiser",
    recommendedTags: ["fundraiser", "gala", "donors", "program", "formal", "nonprofit"],
    recommendedVendors: ["Catering", "AV Production", "Staffing", "Invitations"],
    requiredVendors: ["Venue"],
    season: "fall-spring",
    subtype: "charity gala",
    timeOfDay: "evening",
    venueStyle: "museum, ballroom, hotel, gallery, or event venue",
  },
  {
    aliases: [
      "private party",
      "pool party",
      "block party",
      "holiday party",
      "bbq",
      "barbecue",
      "cookout",
      "housewarming",
      "family reunion",
      "retirement party",
      "festival",
      "church event",
      "school carnival",
    ],
    budgetTier: "standard",
    description: "A flexible social event shaped by location, food style, entertainment, and guest comfort.",
    formality: "casual",
    guestSize: "25-300",
    id: "private-party",
    indoorOutdoor: "indoor-outdoor",
    luxuryAddOns: ["Live Music", "Photo Booth", "Florals"],
    marketplaceEventType: "Private Party",
    optionalVendors: ["Magic", "Character Performers", "Invitations", "Security"],
    primaryType: "Private Party",
    recommendedTags: ["party", "bbq", "barbecue", "cookout", "pool", "backyard", "community"],
    recommendedVendors: ["Catering", "DJ", "Rentals", "Photography"],
    requiredVendors: ["Venue"],
    season: "year-round",
    subtype: "social gathering",
    timeOfDay: "afternoon",
    venueStyle: "home, park, hall, restaurant, or outdoor venue",
  },
];

export function getDefaultProfile() {
  return eventTaxonomyProfiles[0];
}

export function getProfileByMarketplaceType(eventType: EventType) {
  return (
    eventTaxonomyProfiles.find((profile) => profile.marketplaceEventType === eventType) ??
    getDefaultProfile()
  );
}
